[package]
name = "verbihr"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]


[profile.release]
lto = true
codegen-units = 1

[[bin]]
name = "app"
path = "bin/app.rs"

[dependencies]
gloo-console = "0.3.0"
serde = { version = "1.0.192", features = ["derive"] }
serde_yaml = "0.9.27"
wasm-bindgen = "0.2.88"
web-sys = { version = "0.3.65", features = ["Navigator", "MediaQueryList", "Window"] }
yew = { version = "0.21.0", features = ["csr"] }
