[package]
name = "verbihr"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]


[profile.release]
lto = true
codegen-units = 1

[[bin]]
name = "app"
path = "bin/app.rs"

[dependencies]
wasm-bindgen = "0.2.88"
yew = { version = "0.21.0", features = ["csr"] }
